token: "Discord token"
#Время того, сколько можно входить без повторной верификации
time: 60
#Раз в сколько секунд будет проверка для времени выше, лучше не менять
coolDown: 30
#симловы для кода, вдруг понадобится
chars: "0123456789"

